require('plugins.configs.nvimtree')
require('plugins.configs.lualine')

require('plugins.configs.treesitter')
require('plugins.configs.ts-context')
require('plugins.configs.tabout')
require('plugins.configs.lsp')
require('plugins.configs.cmp')
require('plugins.configs.fidget')
require('plugins.configs.colorizer')
require('plugins.configs.impatient')
require('plugins.configs.indentline')
require("plugins.configs.comment")
require('plugins.configs.todo-comment')
require('plugins.configs.gitsigns')
require("plugins.configs.gitblame")
require("plugins.configs.gitlinker")
require('plugins.configs.autopairs')

require('plugins.configs.dial')
require('plugins.configs.numb')

